### ISSUE TITLE
Add log_path config setting, review logging setup

### ISSUE THREAD

**Issue by ozten** [mozilla/browserid-certifier#14]
Via mozilla/browserid-bigtent/issues/121

The stage/prod config needs a log_path config setting for production.json.

 /cc @gene1wood

**Comment by gene1wood** [comment]
What value should it be set to?

**Comment by ozten** [comment]
Fixed in 3976d6d8ac664c571609dcdc3b0c03366b23ef81

Value is the same as browserid, or wherever you want log files to be written.

If you do `"var_path": "/var/certifier"` then logs would go to `/var/certifier/log/certifier.log`.

[Deployment request](https://bugzilla.mozilla.org/show_bug.cgi?id=839211)

**Comment by jrgm** [comment]
Verified. This is logging correctly in staged.
