### ISSUE TITLE
Tweak duration typechecking

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/browserid-certifier#27]
So right now we have the following when handling /cert_key in bin/certifier:

  } else if (typeof req.body.duration !== 'number') {
    return res.json({
      success: false,
      reason: 'duration argument must be a number when present'
    }, 400);

I think we want to cast to a Number and then check bounds for sanity, something like:
  dur = req.body.duration;
  durValid = false;
  if (typeof dur === 'number') {
    durValid = true;
  } else if (typeof dur === 'string') {
     dur = Number(dur);
     if ((0 <= dur) && (dur <= MAX_LEGAL_DURATION)) {
      durValid = true;
     }
  }
  if (!durValid) {
    return res.json({
      success: false,
      reason: 'duration argument must be a number when present, not "' + dur + '"'
    }, 400);
  }
(note also let's report what the bad value was).

**Comment by ozten** [comment]
Good call.

I think we can do `duration = parseInt(dur, 10)` and then check for errors with `isNaN(duration)`.

**Comment by SamPenrose** [comment]
Merged into mozilla/
