### ISSUE TITLE
Automatically look for config/local.json?

### ISSUE THREAD

**Issue by callahad** [mozilla/browserid-certifier#4]
I'd love to be able to just `npm start` a certifier, like I do for BrowserID. Can the certifier default to checking `local/config.json` if the `CONFIG_FILES` envvar is empty?

**Comment by david-caro** [comment]
I've implemented this on my fork, let me test it a little more (and work out the versioning) and I'll make a pull request.

In the meanwhile, the changed file is here: https://github.com/david-caro/browserid-certifier/blob/master/lib/config.js.
Just drop the file in the lib dir and you are good to go :S

**Comment by ozten** [comment]
@david-caro sorry, I didn't see you comment before doing this work.

Be sure to make a "pull request" when you make fixes, but this is my fault.

¡Lo siento amigo!

Fixed in [0e8c58b6f55cf77](https://github.com/mozilla/browserid-certifier/commit/0e8c58b6f55cf77c7763c292fcdce8e95a91d4a4)
