### ISSUE TITLE
Version string

### ISSUE THREAD

**Issue by david-caro** [mozilla/browserid-certifier#6]
Hi,
I'm using the certifier at my work, and the version string does not adapt to the requirements of the company. I'd like to change the version string to something a little more descriptive, here's my proposal (as I explained to fetep):

Major.branch[-num-commits_hash-of-last]

Version string (just modified a little):  MAJOR.tagname/branchname
This is the the closest tag name (or the branch name, if there are no tags before the branch) prepended with the MAJOR (a custom number to reflect a major release, mandatory if the changes made result on a code that is not backwards compatible).

Release string: Num-of-commits_sha
This will be the number of commits since the tag/branch and the short sha of the last commit, to reflect that the code is different in the case of packages from different repos or a rebase (bad rebase!). This can be easily retrieved with the describe command.

Also adding the source repository on the description, to keep track of the source of the code. And the info about the translations.

A sample version string will be this:

0.train_2012.07.15-12_fa3613f

That means the 12th commit after the tag train_2012.07.15. If you commit again, the tag will be something like:

0.train_2012.07.15-13_11fa5d

Even if the hash is not incremental, the version string is incremental (because the number of commits is placed before the hash). And, if you use a different repo with the same tag/branch, and the same number of commits, you see that the hash has changed (that doesn't necessarily mean a bump on the version).

What do you think?

**Comment by david-caro** [comment]
Mmm, viewing that there's no response here, I'm going to ask the same question on the browserid issue tracker... hopefully with more participation :)

**Comment by ozten** [comment]
@fetep thoughts?

**Comment by david-caro** [comment]
I will implement this solution in my fork as soon as possible and request a pull... seen that nobody says nothing, I'll take the lead ;)

To which branch should I request the push?

**Comment by ozten** [comment]
@david-caro please make a pull request against master.

@gene1wood - heads up, we'd like to add some information to our version string.
